<?php
namespace geissler\CSLBundle\Services;

require_once dirname(__FILE__) . '/../../../../../Services/Affix.php';

/**
 * Test class for Affix.
 * Generated by PHPUnit on 2012-03-31 at 02:39:35.
 */
class AffixTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Affix
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Affix;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers geissler\CSLBundle\Services\Affix::format
     */
    public function testFormat() {
        $this->assertEquals('Joe', $this->object->format('Joe'));
    }

    public function testFormat1() {
        $str_Style  =   "<style xmlns=\"http://purl.org/net/xbiblio/csl\" class=\"in-text\" version=\"1.0\"><layout delimiter=\"; \" suffix=\", \"></layout></style>";
        $obj_Doc    =   new \DOMDocument();
        $obj_Doc->loadXML($str_Style);
        $this->object->init($obj_Doc->getElementsByTagName('layout')->item(0));
        $this->assertEquals('Joe, ', $this->object->format('Joe'));
    }
    
    public function testFormat2() {
        $str_Style  =   "<style xmlns=\"http://purl.org/net/xbiblio/csl\" class=\"in-text\" version=\"1.0\"><layout delimiter=\"; \" prefix=\"(\" suffix=\")\"></layout></style>";
        $obj_Doc    =   new \DOMDocument();
        $obj_Doc->loadXML($str_Style);
        $this->object->init($obj_Doc->getElementsByTagName('layout')->item(0));
        $this->assertEquals('(Joe)', $this->object->format('Joe'));
    }
}

?>
