<?php

namespace geissler\CSLBundle\Services;

require_once dirname(__FILE__) . '/../../../../../Services/CSL.php';

/**
 * Test class for CSL.
 * Generated by PHPUnit on 2012-03-31 at 00:38:52.
 */
class CSLTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CSL
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CSL;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testInit() {
        $str_Style      =   "<style \n      xmlns=\"http://purl.org/net/xbiblio/csl\"\n      class=\"in-text\"\n      version=\"1.0\">\n  <info>\n    <id />\n    <title />\n    <updated>2009-08-10T04:49:00+09:00</updated>\n  </info>\n  <citation>\n    <layout delimiter=\"; \" suffix=\".\">\n      <group delimiter=\", \">\n        <names variable=\"author\">\n          <name form=\"short\" />\n        </names>\n        <text variable=\"title\" />\n        <date variable=\"issued\">\n          <date-part name=\"year\" />\n        </date>\n        <group delimiter=\" \">\n          <label form=\"short\" strip-periods=\"false\" variable=\"locator\" />\n          <text variable=\"locator\" />\n        </group>\n      </group>\n    </layout>\n  </citation>\n</style>";        
        $this->assertTrue($this->object->init($str_Style));
    }
    
    public function testInit1() {
        $str_Style      =   "<style \n      xmlns=\"http://purl.org/net/xbiblio/csl\"\n      class=\"in-text\"\n      version=\"1.0\">\n  <info>\n    <id />\n    <title />\n    <updated>2009-08-10T04:49:00+09:00</updated>\n  </info>\n  <citation>\n    <layout prefix=\"(\" suffix=\")\" delimiter=\", \"><text variable=\"citation-number\"/></layout>\n  </citation>\n</style>";        
        $this->assertTrue($this->object->init($str_Style));
    }
    
    /**
     * @covers geissler\CSLBundle\Services\CSL::citation
     * @todo Implement testCitation().
     */
    public function testCitation() {
        $str_Style      =   "<style \n      xmlns=\"http://purl.org/net/xbiblio/csl\"\n      class=\"in-text\"\n      version=\"1.0\">\n  <info>\n    <id />\n    <title />\n    <updated>2009-08-10T04:49:00+09:00</updated>\n  </info>\n  <citation>\n    <layout delimiter=\"; \" suffix=\".\">\n      <group delimiter=\", \">\n        <names variable=\"author\">\n          <name form=\"short\" />\n        </names>\n        <text variable=\"title\" />\n        <date variable=\"issued\">\n          <date-part name=\"year\" />\n        </date>\n        <group delimiter=\" \">\n          <label form=\"short\" strip-periods=\"false\" variable=\"locator\" />\n          <text variable=\"locator\" />\n        </group>\n      </group>\n    </layout>\n  </citation>\n</style>";
        $obj_Book       =   array(
                                array(                                    
                                    "author"=> array(     
                                        array(
                                            "family"=> "Doe", 
                                            "given"=> "John", 
                                            "static-ordering"=> false
                                        )
                                            
                                    ), 
                                    "id"=> "ITEM-1", 
                                    "issued"=> array(
                                        "date-parts"=> array("2000")
                                            ), 
                                        "title"=> "Book A", 
                                        "type"=> "book"
                                    ), 
                                  array(
                                        "author"=> array(
                                            array(
                                                "family"=> "Roe", 
                                                "given"=> "Jane", 
                                                "static-ordering"=> false
                                                )
                                            )
                                        , 
                                        "id"=> "ITEM-2", 
                                        "issued"=> array(
                                            "date-parts"=> array(
                                                array(
                                                    "2001"
                                                )
                                            )
                                        ), 
                                        "title"=> "Book B", 
                                        "type"=> "book"
                                    )
                                );
        $obj_Citation   =   array(
                                array(
                                    "citationID"=> "CITATION-1", 
                                    "citationItems"=> array(
                                        array(
                                            "id"=> "ITEM-1", 
                                            "label"=> "page", 
                                            "locator"=> "100"), 
                                        array(
                                            "id"=> "ITEM-2", 
                                            "label"=> "chapter", 
                                            "locator"=> "200")
                                        )
                                    ),
                                array(
                                    "citationID"=> "CITATION-2", 
                                    "citationItems"=> array(
                                        array(
                                            "id"=> "ITEM-1", 
                                            "label"=> "page", 
                                            "locator"=> "112"))));
        
        
        $this->assertTrue($this->object->init($str_Style));
        $this->assertInternalType('array', $this->object->citation($obj_Book, $obj_Citation));
        $obj_Result =   $this->object->citation($obj_Book, $obj_Citation);
        $this->assertEquals('Doe, Book A, 2000, p. 100; Roe, Book B, 2001, chap. 200.', $obj_Result['CITATION-1']);
        $this->assertEquals('Doe, Book A, 2000, p. 112.', $obj_Result['CITATION-2']);
    }

    /**
     * @covers geissler\CSLBundle\Services\CSL::bibliography
     * @todo Implement testBibliography().
     */
    public function testBibliography() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
